
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Mar 17 13:29:07 CET 2023
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 31;
  public static final int LLCIERRE = 15;
  public static final int POR = 19;
  public static final int CCIERRE = 17;
  public static final int PUNTOYCOMA = 5;
  public static final int PCIERRE = 24;
  public static final int CASE = 47;
  public static final int CAP = 16;
  public static final int FOR = 27;
  public static final int TIPOFLOAT = 8;
  public static final int MENORIGUAL = 33;
  public static final int AND = 28;
  public static final int IGUAL = 48;
  public static final int LLAP = 14;
  public static final int IGUALDAD = 30;
  public static final int OR = 29;
  public static final int DIV = 26;
  public static final int MAIN = 12;
  public static final int IF = 21;
  public static final int MAYORIGUAL = 32;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int TRUE = 37;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int COMA = 40;
  public static final int NEGACION = 41;
  public static final int MENOS = 35;
  public static final int MENOR = 4;
  public static final int MOD = 36;
  public static final int BREAK = 45;
  public static final int VOID = 9;
  public static final int TIPOINT = 6;
  public static final int SWITCH = 44;
  public static final int REAL = 11;
  public static final int MAYOR = 2;
  public static final int ENT = 10;
  public static final int PAP = 23;
  public static final int ELSE = 22;
  public static final int READ = 43;
  public static final int ENUM = 13;
  public static final int IDEN = 3;
  public static final int WHILE = 25;
  public static final int DEFAULT = 46;
  public static final int TIPOBOOL = 7;
  public static final int FALSE = 38;
  public static final int STRUCT = 18;
  public static final int PRINT = 42;
  public static final int MAS = 34;
}

