
package asint;
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Mar 17 12:05:16 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 30;
  public static final int LLCIERRE = 14;
  public static final int POR = 18;
  public static final int CCIERRE = 16;
  public static final int PUNTOYCOMA = 5;
  public static final int PCIERRE = 23;
  public static final int CAP = 15;
  public static final int FOR = 26;
  public static final int TIPOFLOAT = 8;
  public static final int MENORIGUAL = 32;
  public static final int AND = 27;
  public static final int LLAP = 13;
  public static final int IGUALDAD = 29;
  public static final int OR = 28;
  public static final int DIV = 25;
  public static final int MAIN = 11;
  public static final int IF = 20;
  public static final int MAYORIGUAL = 31;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int TRUE = 36;
  public static final int NEW = 38;
  public static final int error = 1;
  public static final int COMA = 39;
  public static final int NEGACION = 40;
  public static final int MENOS = 34;
  public static final int MENOR = 4;
  public static final int MOD = 35;
  public static final int VOID = 9;
  public static final int TIPOINT = 6;
  public static final int MAYOR = 2;
  public static final int ENT = 10;
  public static final int PAP = 22;
  public static final int ELSE = 21;
  public static final int ENUM = 12;
  public static final int IDEN = 3;
  public static final int WHILE = 24;
  public static final int TIPOBOOL = 7;
  public static final int FALSE = 37;
  public static final int STRUCT = 17;
  public static final int MAS = 33;
}

