package ast.Expresions;

public enum KindE {
  SUMA, RESTA, MUL, DIV, MOD, MENOR, MAYOR, AND, OR, IGUALDAD, DISTINTO, MAYORIGUAL, MENORIGUAL,
  MENOS, NEG, ENT, FLOAT, BOOL, IDENTIFICADOR, LLAMADAFUN, ACCESS, ARRAY, ENUM
}
